#!/usr/bin/env bash

function validate_config {
  if [ -z "$OPENAI_API_KEY" ]; then
    exit 1
  fi
}

function get_diff {
  echo $diff
}

function call_openai {
  local diff="$1"
  local prompt="Generate a concise and informative commit message in English based on the following changes:\n\n$diff"
  local payload=$(jq -n --arg prompt "$prompt" '{
    model: "gpt-3.5-turbo",
    messages: [{role: "user", content: $prompt}],
    max_tokens: 100,
    temperature: 0.5
  }')

  curl -s https://api.openai.com/v1/chat/completions \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer $OPENAI_API_KEY" \
    -d "$payload"
}

function main {
  validate_config

  local diff=$(git diff --staged)
  if [[ -z $diff ]]; then
    echo "Nothing in stage. Exiting..."
    exit 1
  fi

  local openai_response=$(call_openai "$diff")
  local commit_message=$(echo "$openai_response" | jq -r '.choices[0].message.content // ""')
  if [[ -z "$commit_message" ]]; then
    echo "Failed to generate ai commit message, openai response: $openai_response"
    exit 2
  fi

  local tmp_file=$(mktemp)
  echo $commit_message > $tmp_file
  git commit -e -F "$tmp_file"
  rm $tmp_file
}

main $*
