#!/usr/bin/env bash

if [ -z "$OPENAI_API_KEY" ]; then
    exit 1
fi

DIFF=$(git diff --staged)
PROMPT="Generate a concise and informative commit message in English based on the following changes:\n\n$DIFF"

JSON_PAYLOAD=$(jq -n --arg prompt "$PROMPT" '{
  model: "gpt-3.5-turbo",
  messages: [{role: "user", content: $prompt}],
  max_tokens: 100,
  temperature: 0.5
}')

RESPONSE=$(curl -s https://api.openai.com/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -d "$JSON_PAYLOAD")


COMMIT_MESSAGE=$(echo "$RESPONSE" | jq -r '.choices[0].message.content // ""')
if [[ -z "$COMMIT_MESSAGE" ]]; then
  echo "Failed to generate ai commit message, openai response: $RESPONSE"
  exit 1
fi

echo "Generated message: $COMMIT_MESSAGE"

